name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.1+2 

environment:
  sdk: ">=3.9.2 <4.0.0"

dependencies:
  intl: ^0.18.0
  flutter:
    sdk: flutter
  
  http: ^1.5.0
  shared_preferences: ^2.1.1
  image_picker: ^1.0.4
  file_picker: ^10.3.0
  permission_handler: ^12.0.1
  path_provider: ^2.1.1
  printing: ^5.10.1
  pdf: ^3.10.0
  url_launcher: ^6.1.11
  open_filex: ^4.7.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true